name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@tiramon'
      - run: npm install @openapitools/openapi-generator-cli -g
      - run: npx @openapitools/openapi-generator-cli generate -i du-market-api.yaml -g typescript-angular -o typescript-angular --additional-properties=npmName=@tiramon/du-market-api,stringEnums=true,supportsES6=true,ngVersion=13.2.0
      - run: npm uninstall tsickle
        working-directory: typescript-angular
      - run: npm install
        working-directory: typescript-angular
      - run: npm run build
        working-directory: typescript-angular
        env:
          NODE_ENV: production
      - run: npm publish
        working-directory: typescript-angular/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production