# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
#          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - run: npm install @openapitools/openapi-generator-cli -g

      - run: npx @openapitools/openapi-generator-cli generate -i du-market-api.yaml -g spring -o spring --additional-properties=interfaceOnly=true,groupId=de.tiramon.du,artifactId=du-market-api,apiPackage=de.tiramon.du.market.api,modelPackage=de.tiramon.du.market.model

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: spring

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy #-s $GITHUB_WORKSPACE/settings.xml
        working-directory: spring
        env:
          GITHUB_TOKEN: ${{ github.token }}
